const products = document.querySelectorAll('.s-item');
const productsJson = [];

products.forEach((product) => {
    productsJson.push({
        title: product.querySelector('.s-item__info').textContent,
        subTitle: product.querySelector('.s-item__info .s-item__subtitle')
            .textContent,
        condition: product.querySelector('.s-item__info span.SECONDARY_INFO')
            .textContent,
        price: product.querySelector(
            '.s-item__info .s-item__details span.s-item__price'
        ).textContent,
        img: product.querySelector('.s-item__image-wrapper img').src,
    });
});

const laptops = [
    {
        title: 'Shop on eBayOpens in a new window or tabBrand New$20.00or Best Offer ',
        subTitle: 'Brand New',
        condition: 'Brand New',
        price: '$20.00',
        img: 'https://ir.ebaystatic.com/rs/v/fxxj3ttftm5ltcqnto1o4baovyl.png',
    },
    {
        title: 'CHEAP FAST Major Brand Windows 11 Laptop i3 i5 i7 4th 16GB RAM 512GB SSD WIFIOpens in a new window or tabWindows 11☑️ 1 Year Warranty☑️High Speed🚀Good - Refurbished£149.99Save up to 10% with Multi-buyRRP £239.99  38% offCustoms services and international tracking providedBuy it nowintelliscope (14,378) 99.8%+ £59.05 postage estimatefrom United KingdomRefurbished73+ sold ',
        subTitle: 'Windows 11☑️ 1 Year Warranty☑️High Speed🚀',
        condition: 'Good - Refurbished',
        price: '£149.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/rf0AAOSwQopkq-Cu/s-l500.webp',
    },
    {
        title: 'CHEAP FAST Top Brand Windows 10/11 Laptop i3/i5 32GB Ram 256GB SSD/ 1TB SSD WIFIOpens in a new window or tab✔️1 YEAR WARRANTY ✔️CHEAPEST ON EBAY ✔️REFURBISHED ✔️Good - Refurbished£119.99 to £329.99  £199.99 per Unit(£199.99/Unit)Save up to 5% with Multi-buyRRP £999.95  80% offeBay Premium ServiceeBay Premium ServiceBuy it nowCustoms services and international tracking provided+ £58.23 postage estimatebirmingham-av (7,995) 98.8%from United KingdomRefurbished ',
        subTitle: '✔️1 YEAR WARRANTY ✔️CHEAPEST ON EBAY ✔️REFURBISHED ✔️',
        condition: 'Good - Refurbished',
        price: '£119.99 to £329.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/ga0AAOSwwnVj-hGL/s-l500.webp',
    },
    {
        title: 'Cheap Fast Windows 10 Laptop CORE i5 8GB RAM 256GB SSD WIFIOpens in a new window or tabGood - Refurbished£79.99 to £114.99Save up to 15% with Multi-buyBuy it noweBay Premium ServiceeBay Premium Service+ £54.09 postage estimateCustoms services and international tracking providedfrom United Kingdomri-services (31,049) 95.7%Free returnsRefurbished147+ sold ',
        subTitle: 'Good - Refurbished',
        condition: 'Good - Refurbished',
        price: '£79.99 to £114.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/yGIAAOSwTkpkkZ9R/s-l500.webp',
    },
    {
        title: 'Laptop HP Windows 11 CORE i5 GEN 6-8 TH 32GB RAM 1TB SSD WEBCAM WIFI DELLOpens in a new window or tabGood - Refurbished£119.99 to £349.99  £209.99 per Unit(£209.99/Unit)eBay Premium ServiceeBay Premium ServiceRRP £1,049.95  80% offCustoms services and international tracking providedBuy it nowbirmingham-av (7,995) 98.8%+ £68.56 postage estimatefrom United KingdomRefurbished20+ sold ',
        subTitle: 'Good - Refurbished',
        condition: 'Good - Refurbished',
        price: '£119.99 to £349.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/onIAAOSw17hk3WLf/s-l500.webp',
    },
    {
        title: 'Lenovo ThinkPad x260 12.5" Laptop 2.50 Ghz Intel Core i5-6200U 8GB 500GB, Win10Opens in a new window or tabPre-owned£54.99Save up to 5% with Multi-buyor Best OffereBay Premium ServiceeBay Premium Service+ £60.22 postage estimateCustoms services and international tracking providedfrom United Kingdomhainault_treasures (11,609) 99.8%Almost gone15 sold ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£54.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/GbQAAOSwmuJl4MHZ/s-l500.webp',
    },
    {
        title: 'Lenovo ThinkPad x260 12.5" Laptop 2.50 Ghz Intel Core i5-6200U 8GB 500GB Win10Opens in a new window or tabPre-owned£64.99Save up to 5% with Multi-buyor Best OffereBay Premium ServiceeBay Premium Service+ £60.56 postage estimateCustoms services and international tracking providedfrom United Kingdomhainault_treasures (11,609) 99.8%35 sold ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£64.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/5QgAAOSwcR5l2hNr/s-l500.webp',
    },
    {
        title: 'Fast iCore Laptop Lenovo Core i3 i5 8GB RAM 128 GB SSD Windows 10 Win HP DellOpens in a new window or tabCheap Notebook Ultrabook WiFi 15.6" 12.5" 14" 13" SizeGood - Refurbished£84.99  £84.99 per Unit(£84.99/Unit)Save up to 7% with Multi-buyor Best Offerrecycly.tech (1,522) 98%+ £45.00 postagefrom United KingdomRefurbished629 sold ',
        subTitle: 'Cheap Notebook Ultrabook WiFi 15.6" 12.5" 14" 13" Size',
        condition: 'Good - Refurbished',
        price: '£84.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/DaYAAOSwVuJlz74J/s-l500.webp',
    },
];

const nokiaBatteries = [
    {
        title: 'Shop on eBayOpens in a new window or tabBrand New$20.00or Best Offer ',
        subTitle: 'Brand New',
        condition: 'Brand New',
        price: '$20.00',
        img: 'https://ir.ebaystatic.com/rs/v/fxxj3ttftm5ltcqnto1o4baovyl.png',
    },
    {
        title: 'Genuine Nokia HE363 Replacement Battery For Nokia 8.1 TA-1099 TA-1113 TA-1115Opens in a new window or tabBrand new£22.99Save up to 10% with Multi-buyBuy it nowmobic9972 (1,550) 98%Postage not specifiedfrom United KingdomFree returns ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£22.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/bkwAAOSwn1BgfvIl/s-l500.webp',
    },
    {
        title: 'BL-4C Battery for NOKIA 890mAH Li-ion (Lithium)Opens in a new window or tabBrand new£5.03eBay Premium ServiceeBay Premium ServiceBuy it nowstainlessqualityprice (1,304) 99.7%+ £0.85 postagefrom France96 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.03',
        img: 'https://i.ebayimg.com/thumbs/images/g/c6wAAOSwgWdlRBuI/s-l500.webp',
    },
    {
        title: 'Genuine Nokia BL-5C Battery for 6108/6230/6230i/6267/6270/6555/6600/6620/6630Opens in a new window or tabBrand new5.0 out of 5 stars.1 product rating - Original Nokia Batterie BL-5C pour 6108/6230/6230i/6267/6270/6555/6600/6620/6630£7.51eBay Premium ServiceeBay Premium ServiceBuy it nowstainlessqualityprice (1,304) 99.7%+ £0.85 postagefrom France64 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£7.51',
        img: 'https://i.ebayimg.com/thumbs/images/g/AfAAAOSw1V9kGwN0/s-l500.webp',
    },
    {
        title: 'Battery for Nokia 3310 1300mAh Li-Ion (BLC-2)Opens in a new window or tabBrand new£6.76eBay Premium ServiceeBay Premium ServiceBuy it nowmobilfunk-krause (373,735) 99.8%+ £2.95 postagefrom Germany610 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£6.76',
        img: 'https://i.ebayimg.com/thumbs/images/g/ixwAAOSw889ePc6l/s-l500.webp',
    },
    {
        title: 'Nokia BL-5C 3.7V 1020mAh Lithium Cellphone BatteryOpens in a new window or tabBrand new4.5 out of 5 stars.293 product ratings - Nokia BL-5C 3.7V 1020mAh Lithium Cellphone Battery£4.69Save up to 9% with Multi-buyBuy it nowbcmparts (93) 98.9%Postage not specifiedfrom United Kingdom92 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£4.69',
        img: 'https://i.ebayimg.com/thumbs/images/g/9C0AAOSw3jtlrT9Q/s-l500.webp',
    },
    {
        title: 'New Nokia BL-5C BATTERY 1020MAH FOR NOKIA 1100 1600 2300 6230 6630 UK SellerOpens in a new window or tabBrand new£3.99shus_7193 (336) 99.7%Buy it nowPostage not specifiedfrom United Kingdom497 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£3.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/DKwAAOSwL6Zkuu6N/s-l500.webp',
    },
    {
        title: 'New BL-5CB Battery For Nokia 100 103 106 105 113 103 1616 X2-05 C1-01UK SELLEROpens in a new window or tabBrand new£5.99  £5.99 per Unit(£5.99/Unit)top-link-4u (3,688) 97.1%Buy it nowPostage not specifiedfrom United Kingdom88 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/mSAAAOSwgkxlXP-s/s-l500.webp',
    },
    {
        title: 'Genuine Nokia 8110 Matrix BananaOpens in a new window or tabPre-owned£80.00steevenson973 (750) 100%0 bids · Time left4d 9h left  (Thu, 22:17)or Best OfferPostage not specifiedfrom United Kingdom ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£80.00',
        img: 'https://i.ebayimg.com/thumbs/images/g/5vQAAOSw~fBl14Eo/s-l500.webp',
    },
    {
        title: 'GENUINE BL-5C BATTERY 1020mAh FOR NOKIA 106 1100 1600 2300 6230 6630 UK STOCKOpens in a new window or tabBrand new4.5 out of 5 stars.293 product ratings - GENUINE BL-5C BATTERY 1020mAh FOR NOKIA 106 1100 1600 2300 6230 6630 UK STOCK£5.99Save up to 20% with Multi-buyBuy it nowam777plus (2,926) 97.2%Postage not specifiedfrom United Kingdom687 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/yvsAAOSwFw1igD4h/s-l500.webp',
    },
    {
        title: 'NEW BLC-2 BATTERY 3.6V FOR 3310 3330 3410 3510 AND VARIOUS NOKIA MOBILE PHONES Opens in a new window or tabBrand new£5.99Save up to 10% with Multi-buyor Best Offermobile.phones.2u (8,240) 99.5%+ £12.49 postagefrom United Kingdom273 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/yN0AAOSw8D9bmO~2/s-l500.webp',
    },
    {
        title: 'NEW NOKIA BLB-2 BATTERY 3.6V FOR 8210 8310 5210 AND VARIOUS NOKIA MOBILE PHONES Opens in a new window or tabBrand new£6.99Save up to 10% with Multi-buyor Best Offermobile.phones.2u (8,240) 99.5%+ £12.49 postagefrom United Kingdom108 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£6.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/61sAAOSwVhFf2kYQ/s-l500.webp',
    },
    {
        title: 'BL-5C Replacement Battery Original BL 5C USB Charger For Nokia Li-ion 3.7V BL5COpens in a new window or tabBrand new£5.05 to £5.59aiwend (116) 97.5%Buy it nowFree international postagefrom China ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.05 to £5.59',
        img: 'https://i.ebayimg.com/thumbs/images/g/NYsAAOSwO~Rksl9d/s-l500.webp',
    },
    {
        title: 'Genuine Nokia / Microsoft BL-T5A Battery For Nokia Lumia 550 730 735  2100mAhOpens in a new window or tabPre-owned£4.75  £4.75 per Unit(£4.75/Unit)eBay Premium ServiceeBay Premium ServiceBuy it nowCustoms services and international tracking provided+ £34.49 postage estimateogeech33 (16,689) 99.4%from United KingdomAlmost gone33 sold ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£4.75',
        img: 'https://i.ebayimg.com/thumbs/images/g/FyYAAOSw0zBfXlTv/s-l500.webp',
    },
    {
        title: 'Genuine Nokia HE336 Battery For Nokia 3.1, 5.1 - 2900mAhOpens in a new window or tabBrand new£19.99Save up to 12% with Multi-buyBuy it nowmobic9972 (1,550) 98%Postage not specifiedfrom United KingdomFree returns ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£19.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/Z5sAAOSw7ftgfukv/s-l500.webp',
    },
    {
        title: 'Brand new Genuine Nokia BL-5H Battery For Nokia Lumia 630 638 635 636 1830mAhOpens in a new window or tabBrand new£19.99  £19.99 per Unit(£19.99/Unit)Save up to 12% with Multi-buyBuy it nowmobic9972 (1,550) 98%Postage not specifiedfrom United KingdomFree returns ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£19.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/150AAOSw7JRhDBfk/s-l500.webp',
    },
    {
        title: 'BRAND NEW GENUINE NOKIA / MICROSOFT BATTERY BL-T5A FOR NOKIA LUMIA 550 730 735 2Opens in a new window or tabBrand new5.0 out of 5 stars.1 product rating - BRAND NEW GENUINE NOKIA / MICROSOFT BATTERY BL-T5A FOR NOKIA LUMIA 550 730 735 2£19.99Save up to 12% with Multi-buyBuy it nowmobic9972 (1,550) 98%Postage not specifiedfrom United KingdomFree returns ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£19.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/im8AAOSwwnxg~uk3/s-l500.webp',
    },
    {
        title: 'Battery Fits Nokia 8810 BMP-1A BMP-1D BMP-2L Accu Battery Battery Chrome NEWOpens in a new window or tabBrand new£34.17eBay Premium ServiceeBay Premium ServiceBuy it nowmoelectronix (81,052) 99.2%+ £8.48 postagefrom Germany339 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£34.17',
        img: 'https://i.ebayimg.com/thumbs/images/g/U3AAAOSwFFVd3anL/s-l500.webp',
    },
    {
        title: '🔥Replacement Nokia BL5C BATTERY C2 01 02 03 06 C1 7600 N70 1100 1600 2300 6230Opens in a new window or tabBrand new£2.99eBay Premium ServiceeBay Premium ServiceBuy it nowCustoms services and international tracking provided+ £34.43 postage estimateontel2019 (10,622) 97.9%from United Kingdom1,296 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£2.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/txgAAOSwWHNlr-Zj/s-l500.webp',
    },
    {
        title: 'GENUINE NOKIA BL-5CB BATTERY FOR 100 - C1-01 - 1800 - 1616 - 106 - 105 - 113Opens in a new window or tabPre-owned£4.99Customs services and international tracking providedBuy it nowtalk-smart (2,940) 98.3%+ £34.50 postage estimatefrom United Kingdom ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£4.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/IzEAAOSwVNxgNqEc/s-l500.webp',
    },
    {
        title: 'Battery for Nokia 6500 Slide 900mAh Li-Ion (BP-5M)Opens in a new window or tabBrand new£5.91eBay Premium ServiceeBay Premium ServiceBuy it nowmobilfunk-krause (373,735) 99.8%+ £2.95 postagefrom Germany66 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.91',
        img: 'https://i.ebayimg.com/thumbs/images/g/O9oAAOSwjZJaAibX/s-l500.webp',
    },
    {
        title: 'Genuine Nokia BL-5B Battery for N80 N83 6021 5300 5208 5140 6020 6060 5320 7360Opens in a new window or tabPre-owned£3.89Save up to 5% with Multi-buyBuy it nowCustoms services and international tracking provided+ £35.45 postage estimatetech2talk (8,505) 99.1%from United Kingdom147 sold ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£3.89',
        img: 'https://i.ebayimg.com/thumbs/images/g/N6oAAOSw46JgIz0N/s-l500.webp',
    },
    {
        title: 'Battery for Nokia Lumia 710 1000mAh Li-Ion (BP-3L)Opens in a new window or tabBrand new£5.91eBay Premium ServiceeBay Premium ServiceBuy it nowmobilfunk-krause (373,735) 99.8%+ £2.95 postagefrom Germany ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.91',
        img: 'https://i.ebayimg.com/thumbs/images/g/RW8AAOSw6VRaAiZT/s-l500.webp',
    },
    {
        title: 'BL-6Q BL6Q Battery AND CHARGER FOR Nokia 6700 Classic 7900 6700C 8500 6100s Opens in a new window or tabBrand new£11.85 to £15.02eBay Premium ServiceeBay Premium ServiceBuy it nowxmb-123 (350) 97.3%Free international postagefrom China ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£11.85 to £15.02',
        img: 'https://i.ebayimg.com/thumbs/images/g/qnoAAOSwSZtiMZz1/s-l500.webp',
    },
    {
        title: 'New Replacement BL-4C / BL4C Battery for Nokia Mobile Phones. 5100 6100 6300 etcOpens in a new window or tabBrand new£7.98Customs services and international tracking providedWas: £8.40  5% off*m99* (123,884) 99.2%Buy it now+ £34.61 postage estimatefrom United Kingdom135 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£7.98',
        img: 'https://i.ebayimg.com/thumbs/images/g/vywAAOSw9R1ZoV9S/s-l500.webp',
    },
    {
        title: '1000mah Battery FOR NOKIA 3310 3330 3510 5510 6800Opens in a new window or tabPre-owned£2.49Customs services and international tracking providedBuy it nowcarexpert20 (8,067) 99.1%+ £34.42 postage estimatefrom United Kingdom ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£2.49',
        img: 'https://i.ebayimg.com/thumbs/images/g/~kUAAOSwrJpl1oSR/s-l500.webp',
    },
    {
        title: 'BATTERY FOR NOKIA BL-5C BL5C ASHA 202 100/101/113/222/1100/1101/1110/1110i2600Opens in a new window or tabBrand new£5.88eBay Premium ServiceeBay Premium ServiceBuy it nowstainlessqualityprice (1,304) 99.7%+ £0.85 postagefrom France ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.88',
        img: 'https://i.ebayimg.com/thumbs/images/g/IvYAAOSwTxtl12N6/s-l500.webp',
    },
    {
        title: 'Original BML-3 battery for Nokia 3210Opens in a new window or tabNew (other)£16.27originalclassicphonesnl (46) 96.9%Buy it now+ £13.70 postagefrom Netherlands ',
        subTitle: 'New (other)',
        condition: 'New (other)',
        price: '£16.27',
        img: 'https://i.ebayimg.com/thumbs/images/g/09cAAOSwYNhlhVHS/s-l500.webp',
    },
    {
        title: 'Battery for Nokia Blb-2 BLB2 for 5210 6510 7650 8210 8250 8270 8310 8890 8910Opens in a new window or tabBrand new£9.91  £9.91 per Unité(£9.91/Unité)eBay Premium ServiceeBay Premium ServiceBuy it nowstainlessqualityprice (1,304) 99.7%+ £0.85 postagefrom France ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£9.91',
        img: 'https://i.ebayimg.com/thumbs/images/g/gLQAAOSw9FVl2M0z/s-l500.webp',
    },
    {
        title: 'New Nokia BL-4CT Battery 860mAh For Nokia 2720 5310 5630 6600 7210 Slide 7230 X3Opens in a new window or tabBrand new£5.99top-link-4u (3,688) 97.1%Buy it nowPostage not specifiedfrom United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/T-UAAOSwKm1lXPmJ/s-l500.webp',
    },
    {
        title: 'New High Quality BLB-2 Battery For Nokia 8210 8310 6510 6590 7650 5210 8850Opens in a new window or tabBrand new5.0 out of 5 stars.23 product ratings - New High Quality BLB-2 Battery For Nokia 8210 8310 6510 6590 7650 5210 8850£4.50top-link-4u (3,688) 97.1%Buy it nowPostage not specifiedfrom United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£4.50',
        img: 'https://i.ebayimg.com/thumbs/images/g/paEAAOSwuD1lXQBe/s-l500.webp',
    },
    {
        title: 'NEW Nokia BLB-2 battery, For Nokia 5210 6510 6590 7650 8210 8310 8890Opens in a new window or tabBrand new£2.79  £2.79 per Unit(£2.79/Unit)Customs services and international tracking providedBuy it nowmm.techno (1,159) 97.6%+ £34.43 postage estimatefrom United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£2.79',
        img: 'https://i.ebayimg.com/thumbs/images/g/HqsAAOSwySplZPAx/s-l500.webp',
    },
    {
        title: 'New Nokia BL-4C Battery, 890mAh, For Nokia MOBILESOpens in a new window or tabBrand new£3.49Customs services and international tracking providedBuy it nowmrtech.london_4 (1,879) 98.2%+ £34.45 postage estimatefrom United Kingdom84 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£3.49',
        img: 'https://i.ebayimg.com/thumbs/images/g/GroAAOSwJ45lZPTe/s-l500.webp',
    },
    {
        title: 'ORIGINAL NOKIA 8800 BLACK SILVER GOLD BATTERY BP-6X FULL OEM NOSOpens in a new window or tabBrand new£18.17redanasl (235) 100%or Best Offer+ £5.53 postagefrom Lithuania44 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£18.17',
        img: 'https://i.ebayimg.com/thumbs/images/g/nMAAAOSw~nFfo~TP/s-l500.webp',
    },
    {
        title: '100% NEW ORIGINAL BATTERY FOR NOKIA 5310 5630 Xpress Music 7210 -/ BL-4CTOpens in a new window or tabBrand new£5.91eBay Premium ServiceeBay Premium ServiceBuy it nowhdcell (414) 98.1%Free international postagefrom FranceFree returns ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.91',
        img: 'https://i.ebayimg.com/thumbs/images/g/xn0AAOSwF69lv90d/s-l500.webp',
    },
    {
        title: '1600MAH HDCELL BATTERY FOR NOKIA 5230 5800 5228 5235 Asha 200 201 302 LUMIA BL-5JOpens in a new window or tabBrand new£5.91eBay Premium ServiceeBay Premium ServiceBuy it nowhdcell (414) 98.1%Free international postagefrom FranceFree returns ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.91',
        img: 'https://i.ebayimg.com/thumbs/images/g/l84AAOSwQA1kMVmk/s-l500.webp',
    },
    {
        title: 'Joblot Original Nokia BPS-2  , BLS-2H  Battery For 6310i, 6310, 6210 - UNTESTEDOpens in a new window or tabParts only4.0 out of 5 stars.5 product ratings - Joblot Original Nokia BPS-2  , BLS-2H  Battery For 6310i, 6310, 6210 - UNTESTED£14.99Customs services and international tracking providedor Best Offerskha82159 (1,927) 100%+ £34.85 postage estimatefrom United Kingdom ',
        subTitle: 'Parts only',
        condition: 'Parts only',
        price: '£14.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/cv4AAOSw8aRlontf/s-l500.webp',
    },
    {
        title: 'Battery MaxPower for Nokia 6021 1100mAh Li-Ion (BL-5B)Opens in a new window or tabBrand new£7.62eBay Premium ServiceeBay Premium ServiceBuy it nowmobilfunk-krause (373,735) 99.8%+ £2.95 postagefrom Germany106 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£7.62',
        img: 'https://i.ebayimg.com/thumbs/images/g/7soAAOSw38hgJcYk/s-l500.webp',
    },
    {
        title: 'Brand New Nokia Battery WT340 For Nokia G10 G20 TA-1336 TA-1343 TA-1347 TA-1372Opens in a new window or tabBrand new£14.50Save up to 20% with Multi-buyBuy it nowCustoms services and international tracking provided+ £34.83 postage estimatemape-store (1,279) 99.4%from United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£14.50',
        img: 'https://i.ebayimg.com/thumbs/images/g/gYwAAOSwSF9kNtm9/s-l500.webp',
    },
    {
        title: 'NEW NOKIA Battery BL-4UOpens in a new window or tabBrand new£2.95  £2.95 per Unit(£2.95/Unit)Customs services and international tracking providedBuy it nowmm.techno (1,159) 97.6%+ £34.43 postage estimatefrom United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£2.95',
        img: 'https://i.ebayimg.com/thumbs/images/g/kQYAAOSwUF5lcDbE/s-l500.webp',
    },
    {
        title: 'New Nokia BL-4C Battery, 890mAh, For Nokia , Fast DeliveryOpens in a new window or tabBrand new£2.99Customs services and international tracking providedBuy it nowmagicotech-8 (1,117) 97.7%+ £34.43 postage estimatefrom United Kingdom54 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£2.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/aPcAAOSw-19lZLaq/s-l500.webp',
    },
    {
        title: 'Genuine BL-5CT Battery For Nokia 6303 CLASSIC 6303i C5-00 C6-01 C3 3720 5220Opens in a new window or tabOpened – never used£4.25  £4.25 per Unit(£4.25/Unit)eBay Premium ServiceeBay Premium ServiceBuy it nowCustoms services and international tracking provided+ £34.48 postage estimateogeech33 (16,689) 99.4%from United Kingdom ',
        subTitle: 'Opened – never used',
        condition: 'Opened – never used',
        price: '£4.25',
        img: 'https://i.ebayimg.com/thumbs/images/g/ofIAAOSw-NZiRHpd/s-l500.webp',
    },
    {
        title: 'BATTERY BLC-2 FOR OLD NOKIA PHONE 3310 3330 3410 3510 5510 6800Opens in a new window or tabBrand new£6.89Save up to 15% with Multi-buyBuy it nowCustoms services and international tracking provided+ £41.65 postage estimateaas-777 (2,511) 98.7%from United Kingdom121 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£6.89',
        img: 'https://i.ebayimg.com/thumbs/images/g/WdkAAOSwTipjKhyo/s-l500.webp',
    },
    {
        title: 'Battery for Nokia 2720 flip / 8110 replacement battery battery battery BV-6A 1500mAhOpens in a new window or tabBrand new£10.27fialde2014 (47,960) 99%Buy it now+ £8.56 postagefrom Germany280 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£10.27',
        img: 'https://i.ebayimg.com/thumbs/images/g/7ekAAOSwUF1kX4AO/s-l500.webp',
    },
    {
        title: 'Genuine Batterry BL-5C FOR NOKIA 3110,N70,6630,6680,6230i,2310,3650,3660Opens in a new window or tabPre-owned£2.99Customs services and international tracking providedBuy it nowcarexpert20 (8,067) 99.1%+ £34.43 postage estimatefrom United Kingdom13 sold ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£2.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/y10AAOSw4PllDNwP/s-l500.webp',
    },
    {
        title: 'ORIGINAL NOKIA OEM BL5CB BL-5CB 800mAh 3.0Wh 3.7V ORIGINAL BATTERYOpens in a new window or tabBrand new£8.48  £8.48 per Unité(£8.48/Unité)eBay Premium ServiceeBay Premium ServiceBuy it nowmister-phone (29,935) 100%+ £4.20 postagefrom France ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£8.48',
        img: 'https://i.ebayimg.com/thumbs/images/g/ZyIAAOSw38FkDMnJ/s-l500.webp',
    },
    {
        title: 'GENUINE NOKIA BP-4L E52 E55 E63 E71 E72 E73 E90 N810 N97 ORIGINAL BATTERYOpens in a new window or tabBrand new£11.05  £11.05 per Unité(£11.05/Unité)eBay Premium ServiceeBay Premium ServiceBuy it nowmister-phone (29,935) 100%+ £4.20 postagefrom France17 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£11.05',
        img: 'https://i.ebayimg.com/thumbs/images/g/iQUAAOSwClBgu-46/s-l500.webp',
    },
    {
        title: 'Battery for Nokia 1680 Classic 750mAh Li-Ion (BL-4C)Opens in a new window or tabBrand new£5.91eBay Premium ServiceeBay Premium ServiceBuy it nowmobilfunk-krause (373,735) 99.8%+ £2.95 postagefrom Germany ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.91',
        img: 'https://i.ebayimg.com/thumbs/images/g/OGoAAOSweaBePXC-/s-l500.webp',
    },
    {
        title: ' BL-5F NOKIA Replacement Battery for Nokia N95, N96, E65 950mAhOpens in a new window or tabBrand new£2.99Save up to 20% with Multi-buyBuy it nowCustoms services and international tracking provided+ £34.43 postage estimateseptal (9,001) 99.2%from United Kingdom372 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£2.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/rKoAAOSwX1VgU8ED/s-l500.webp',
    },
    {
        title: 'Genuine Nokia BL-4J Battery For Nokia C6 C6-00 5230 5800 Lumia 620 1200mAhOpens in a new window or tabBrand new£2.85  £2.85 per Unit(£2.85/Unit)eBay Premium ServiceeBay Premium ServiceBuy it nowCustoms services and international tracking provided+ £34.43 postage estimateogeech33 (16,689) 99.4%from United Kingdom79 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£2.85',
        img: 'https://i.ebayimg.com/thumbs/images/g/aXUAAOSwuoZfXl6s/s-l500.webp',
    },
    {
        title: '100% NEW ORIGINAL BATTERY FOR NOKIA 2505 2630 2660 N76 7380 7070 N75 -BL-4BOpens in a new window or tabBrand new£5.05eBay Premium ServiceeBay Premium ServiceBuy it nowhdcell (414) 98.1%Free international postagefrom FranceFree returns ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.05',
        img: 'https://i.ebayimg.com/thumbs/images/g/1sQAAOSwn65l24o4/s-l500.webp',
    },
    {
        title: 'BL-5C BATTERY REPLACEMENT 1020MAH FOR NOKIA 1100 1600 2300 6230 6630Opens in a new window or tabBrand new£5.39 to £24.82eBay Premium ServiceeBay Premium ServiceBuy it nowgogoshopping888 (42,289) 96%+ £3.58 postagefrom China ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£5.39 to £24.82',
        img: 'https://i.ebayimg.com/thumbs/images/g/oHcAAOSwpmRl0Hhp/s-l500.webp',
    },
    {
        title: 'BRAND NEW GENUINE NOKIA BP-6MT BATTERY FOR E51 - N81 - N82 - 5610 - 6270COpens in a new window or tabBrand new£15.99Customs services and international tracking providedBuy it nowtalk-smart (2,940) 98.3%+ £34.88 postage estimatefrom United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£15.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/cOQAAOSw1kxkbQEH/s-l500.webp',
    },
    {
        title: 'Battery for Nokia 7280 7380 Battery Lion 900mAh (Tipo BL-8N) NEWOpens in a new window or tabBrand new£29.97robles-shop (3,695) 99.4%Buy it now+ £12.84 postagefrom Germany9 watchers ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£29.97',
        img: 'https://i.ebayimg.com/thumbs/images/g/EUEAAOSwTmpkQZ1t/s-l500.webp',
    },
    {
        title: 'Nokia WT140 BATTERY FOR Nokia C01 Plus TA-1396 3000MAHOpens in a new window or tabBrand new£12.00Save up to 15% with Multi-buyBuy it nowCustoms services and international tracking provided+ £34.74 postage estimatemape-store (1,279) 99.4%from United Kingdom155 sold ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£12.00',
        img: 'https://i.ebayimg.com/thumbs/images/g/tfoAAOSw7Jhj9kbx/s-l500.webp',
    },
    {
        title: 'Nokia Button Phone Battery  BL-5B  BL5B 3.7v  Nokia Replacement Battery 3.7 VoltOpens in a new window or tabPre-owned£4.27trades66 (10) 100%Buy it now+ £2.56 postagefrom Ireland ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£4.27',
        img: 'https://i.ebayimg.com/thumbs/images/g/stYAAOSwNXZl26eX/s-l500.webp',
    },
    {
        title: 'Genuine  Battery For Nokia 110 101 107 Dual Sim 114 130 150 Asha 202 203 BL-5COpens in a new window or tabPre-owned£5.99Customs services and international tracking providedBuy it nowgsmstore (1,584) 100%+ £34.54 postage estimatefrom United Kingdom ',
        subTitle: 'Pre-owned',
        condition: 'Pre-owned',
        price: '£5.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/dp4AAOSwmsFkizfn/s-l500.webp',
    },
    {
        title: 'Festival MOBILE PHONE CHARGER Sony Ericsson Motorola Nokia iPod i3 old old 2x AAOpens in a new window or tabBrand new£3.99Customs services and international tracking providedBuy it nowroyroyroy6 (1,990) 98.5%+ £34.47 postage estimatefrom United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£3.99',
        img: 'https://i.ebayimg.com/thumbs/images/g/RegAAOSw5rZhv2Ay/s-l500.webp',
    },
    {
        title: 'Genuine Nokia BL-5CT Battery For Nokia C3 C5 C6-01 5220 5630 6303 1050mAhOpens in a new window or tabBrand new£4.75  £4.75 per Unit(£4.75/Unit)eBay Premium ServiceeBay Premium ServiceBuy it nowCustoms services and international tracking provided+ £34.49 postage estimatebuntytech_2017 (31,667) 99.2%from United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£4.75',
        img: 'https://i.ebayimg.com/thumbs/images/g/Z~oAAOSwE9hll-OR/s-l500.webp',
    },
    {
        title: 'NEW Nokia Battery BL-4UL, 1200 mAh, FOR NOKIA ASHA 225, 230, 3310 (2017)Opens in a new window or tabBrand new£4.49  £4.49 per Unit(£4.49/Unit)Customs services and international tracking providedBuy it nowmagicotech-8 (1,117) 97.7%+ £34.48 postage estimatefrom United Kingdom ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£4.49',
        img: 'https://i.ebayimg.com/thumbs/images/g/DusAAOSw-WxlZMq0/s-l500.webp',
    },
    {
        title: 'Battery for NOKIA Blc-2 BLC2 3310 3330 3360 3385 3390 3410 3510 5510 6651 6810Opens in a new window or tabBrand new£9.74  £9.74 per Unité(£9.74/Unité)eBay Premium ServiceeBay Premium ServiceBuy it nowstainlessqualityprice (1,304) 99.7%+ £0.85 postagefrom France ',
        subTitle: 'Brand new',
        condition: 'Brand new',
        price: '£9.74',
        img: 'https://i.ebayimg.com/thumbs/images/g/TroAAOSwtzZl2NQ0/s-l500.webp',
    },
];
